# .streamlit/secrets.toml

OPENAI_API_KEY = "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"

[connections.snowflake]
user = "YMONDONGUE"
password = "Mo27ya55&***"
warehouse = "WH_MARCHE_PUBLIC"
role = "ACCOUNTADMIN"
account = "aylqpwf-nextdecision_partner"

